apiVersion: v1
kind: Service
metadata:
  name: java-app-svc
  annotations:
    networking.gke.io/load-balancer-type: "External"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: java-app
  ports:
  - name: tcp-port
    protocol: TCP
    port: 80
    targetPort: 8080
